### ISSUE TITLE
Clumsy phrasing in README

### ISSUE THREAD

**Issue by jrbinks** [smck83/expurgate#1]
This:

"With organisations focusing on DMARC over the past 5 years that rely on SPF and DKIM to prevent domain spoofing, there has never been more reason for an organisation to exceed the 10 host resolution lookup limit."

appears to be very clumsily re-phrased, so just a suggestion to see if you can re-write it more clearly :). 

J.

**Comment by smck83** [comment]
Happy to change it if you have a suggestion of something less clumsy to change it to.
